version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    image: nelsonbaez/backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: nelsonbaez/frontend
    ports:
      - "5173:5173"

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
